# OpenCode Configuration

version: "1.0"

# OpenCode AI Platform Integration
opencode:
  enabled: true
  install_url: "https://opencode.ai/install"
  
  # Global setup
  global: true
  
  # Custom agents integration
  agents:
    enabled: true
    path: ".github/agents"
    
    # Agent configurations
    agents_list:
      - name: "code-reviewer"
        type: "review"
        trigger: ["pull_request"]
        
      - name: "documentation"
        type: "docs"
        trigger: ["push"]
        
      - name: "security-scanner"
        type: "security"
        trigger: ["pull_request", "push"]
        
      - name: "test-generator"
        type: "testing"
        trigger: ["pull_request"]

  # Skills configuration
  skills:
    enabled: true
    path: ".github/skills"
    
  # Workflows integration
  workflows:
    enabled: true
    path: ".github/workflows"
    auto_trigger: true

# Development environment
environment:
  container: "devcontainer"
  
  # Language runtimes
  runtimes:
    node:
      version: "24"
      package_managers: ["npm", "pnpm"]
      
    python:
      version: "3.12"
      package_manager: "pip"
      
    rust:
      enabled: true
      components: ["rustfmt", "clippy"]
      
  # Package managers
  package_managers:
    conda:
      enabled: true
      auto_init: true
      
    npm:
      enabled: true
      global_packages: ["pnpm"]
      
  # System setup
  system:
    users:
      - name: "app"
        sudo: true
        primary: true
        
      - name: "bkg"
        sudo: true
        
    workspace: "/workspace"
    
# OpenAgents integration
openagents:
  enabled: true
  repository: "https://github.com/darrenhinde/OpenAgents"
  install_path: "/opt/openagents"
  
  # Agent capabilities
  capabilities:
    - "code_analysis"
    - "documentation"
    - "testing"
    - "security_scanning"
    - "workflow_automation"

# Automation features
automation:
  pull_requests:
    auto_label: true
    auto_assign: true
    auto_review: true
    
  merge:
    auto_merge_labels: ["auto-merge", "automerge"]
    require_checks: true
    merge_method: "squash"
    
  close:
    auto_close_labels: ["wont-fix", "duplicate", "invalid", "close"]
    cleanup_branch: true

# Security settings
security:
  scan_on_pr: true
  block_vulnerabilities: false
  notify_maintainers: true
